"use client";

import { FormEvent, useEffect, useState } from "react";

type Ticket = { id: string; ticketCode: string; status: string; eventTitle: string; startsAt: string; venue: string };

export default function AccountPage() {
  const [mode, setMode] = useState<"signin" | "signup">("signin");
  const [account, setAccount] = useState<{ email: string; displayName: string } | null>(null);
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [form, setForm] = useState({ displayName: "", email: "", password: "" });
  const [message, setMessage] = useState("");
  const [privacyMessage, setPrivacyMessage] = useState("");

  async function loadTickets() { const response = await fetch("/api/account/tickets", { cache: "no-store" }); if (response.ok) setTickets((await response.json()).tickets || []); }
  useEffect(() => { fetch("/api/account", { cache: "no-store" }).then((response) => response.json()).then((data) => { if (data.authenticated) { setAccount(data.account); loadTickets(); } }).catch(() => undefined); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/account", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: mode, ...form }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setMessage(data.error || "Account sign-in failed."); return; } setAccount(data.account); await loadTickets(); }
  async function requestPrivacy(requestType: "export" | "erase") { const response = await fetch("/api/account/gdpr", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestType }) }); const data = await response.json().catch(() => ({})); setPrivacyMessage(response.ok ? `Your ${requestType} request has been recorded for the Hilston Park team.` : data.error || "Your privacy request could not be recorded."); }
  if (account) return <main className="page-shell"><header className="subbar"><span className="brand"><span className="brand-mark">Hilston Park</span></span><span className="status-pill">My tickets</span></header><section className="content-section"><p className="eyebrow">Welcome back</p><h1>{account.displayName || "Your tickets"}</h1><p className="lead-copy">Your confirmed event tickets and QR codes are available below.</p><div className="ticket-history">{tickets.length ? tickets.map((ticket) => <article className="ticket-history-card" key={ticket.id}><div><p className="eyebrow">{new Date(ticket.startsAt).toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "long", year: "numeric" })}</p><h2>{ticket.eventTitle}</h2><p>{ticket.venue}</p><code>{ticket.ticketCode}</code><small>{ticket.status === "checked_in" ? "Checked in" : "Ready to scan"}</small></div><img src={`/api/account/tickets/${encodeURIComponent(ticket.ticketCode)}/qr`} alt={`QR code for ${ticket.eventTitle}`} /></article>) : <p className="form-note">No confirmed tickets are linked to this email yet.</p>}</div><section className="account-panel"><p className="eyebrow">Privacy</p><h2>Your data</h2><p>Request a copy of your account information or ask the team to review an erasure request.</p>{privacyMessage && <p className="form-note">{privacyMessage}</p>}<div className="button-row"><button className="secondary-link" type="button" onClick={() => requestPrivacy("export")}>Request export</button><button className="secondary-link" type="button" onClick={() => requestPrivacy("erase")}>Request erasure</button></div></section></section></main>;
  return <main className="auth-gate"><section className="auth-gate-panel"><p className="eyebrow">Hilston Park tickets</p><h1>{mode === "signin" ? "Find your tickets." : "Create your account."}</h1><p>{mode === "signin" ? "Sign in to view your confirmed bookings and QR tickets." : "Use the email address from your event booking."}</p><form className="enquiry-form" onSubmit={submit}>{mode === "signup" && <label>Your name<input value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} required /></label>}<label>Email address<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} required /></label><label>Password<input type="password" minLength={12} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} required /></label>{message && <p className="form-error" role="alert">{message}</p>}<button className="primary-button" type="submit">{mode === "signin" ? "Sign in" : "Create account"}</button></form><button className="secondary-link account-mode-switch" type="button" onClick={() => { setMode(mode === "signin" ? "signup" : "signin"); setMessage(""); }}>{mode === "signin" ? "Create an account" : "I already have an account"}</button></section></main>;
}